accent = "#be95ff"
cursor = "#f2f4f8"
foreground = "#f2f4f8"
background = "#161616"
selection_foreground = "#2a2a2a"
selection_background = "#f2f4f8"

color0 = "#484848"
color1 = "#ee5396"
color2 = "#4242B1"
color3 = "#25be6a"
color4 = "#be95ff"
color5 = "#E0E27B"
color6 = "#08bdba"
color7 = "#dfdfe0"
color8 = "#484848"
color9 = "#ee5396"
color10 = "#4242B1"
color11 = "#25be6a"
color12 = "#be95ff"
color13 = "#E0E27B"
color14 = "#08bdba"
color15 = "#dfdfe0"
